ALTER TABLE deployments ADD COLUMN IF NOT EXISTS started_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE deployments ADD COLUMN IF NOT EXISTS destroyed_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE ephemeral_environments ADD COLUMN IF NOT EXISTS started_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE ephemeral_environments ADD COLUMN IF NOT EXISTS destroyed_at TIMESTAMP WITH TIME ZONE;
